### ISSUE TITLE
Merge original/black?

### ISSUE THREAD

**Issue by Astrantia** [philsinatra/popping-and-locking-vscode-black#1]
Now I have both [original](https://github.com/hedinne/popping-and-locking-vscode) and [black](https://github.com/philsinatra/popping-and-locking-vscode-black/) installed as I like to switch between one and the other. 

Why don't we open a PR to add a black theme in the original repo instead of forking away and maintaining a separate repo?

@philsinatra

**Comment by philsinatra** [comment]
What do you feel would be the benefit? I'm not sure the author of the original theme wants to maintain two versions.
