### ISSUE TITLE
A border for active tab

### ISSUE THREAD

**Issue by nd3w** [philsinatra/popping-and-locking-vscode-black#2]
First thanks for this beautiful color theme. 
I would like a suggestion for active tab to use a border, because for me the color of active tab doesn't contrast enough.
I see this implementation on Moonlight (at bottom) and Noctis (at the top).
Thank you.

**Comment by philsinatra** [comment]
Thanks for the feedback. Based on your request, I've added a subtle border to the active tab. Version 1.1.7 has been published to the Marketplace. 🍻
