### ISSUE TITLE
Highlighting in context (right-click) menus is indistinguishable from non-highlighted items.

### ISSUE THREAD

**Issue by makeway4pK** [philsinatra/popping-and-locking-vscode-black#3]
![Screenshot (49)](https://user-images.githubusercontent.com/47619514/78967670-c1464800-7b20-11ea-9c49-3f49bfad56ae.png)

Thanks for this all black theme that works

**Comment by makeway4pK** [comment]
In the above screenshot, the mouse cursor was on "Install Another Version" see if you can figure that out. This is not a problem when using a mouse cursor.

But most coders don't use a mouse often and vscode itself is geared towards keyboard shortcuts.

**Comment by philsinatra** [comment]
Can you explain exactly what you are looking to have "figured out"? Or can you give me the keyboard commands you're executing to work with the popup menu?

**Comment by makeway4pK** [comment]
![Screenshot (50)](https://user-images.githubusercontent.com/47619514/79072637-bc8bba80-7cff-11ea-9d5e-533e56f07a71.png)
This, in the right click menu, the menu item highlight color is very difficult to see. So, if I'm operating this menu from the keyboard, it is very difficult to know which option will be pressed when I hit enter.

If you simply change the highlight color in right click menus, also called context menus, this will be solved.

**Comment by makeway4pK** [comment]
Just for clarity, here's the right-click menu in the default dark theme:
The blue color is important, it doesn't have to be blue, but it has to be there:
![image](https://user-images.githubusercontent.com/47619514/79072904-23f63a00-7d01-11ea-94f1-99fc601e757e.png)

**Comment by makeway4pK** [comment]
found this at https://github.com/wesbos/cobalt2-vscode/issues/124#issuecomment-432871171
:
```
"workbench.colorCustomizations": {
		"[Popping and Locking Black Theme]": {
			"menu.selectionBackground": "#000000af",
	},

```

**Comment by philsinatra** [comment]
Are you sure you don't have a conflict somewhere? There is a background color for a menu selection already in place.

![Screen Shot 2020-04-13 at 11 16 24 AM](https://user-images.githubusercontent.com/1465808/79132432-52fbc280-7d78-11ea-94e4-74cc17199c5d.png)

**Comment by makeway4pK** [comment]
No, I don't think so.
To be sure, I installed your theme on a vanilla copy of vscode-portable and still the menu looks exactly the same.
 The text of selection gets increased weight ever so slightly but is not noticeable at a glance.

I'm on Windows.

**Comment by philsinatra** [comment]
I'm not able to reproduce this scenario. Does adding the customization you outlined above to your JSON preferences add the color you need?

**Comment by makeway4pK** [comment]
yes, I'm using these customizations:
```
"workbench.colorCustomizations": {
		"[Popping and Locking Black Theme]": {
			"menu.selectionBackground": "#000000af",
			"editorIndentGuide.activeBackground": "#d79921",
			"tree.indentGuidesStroke": "#d79921"
		},
	},
```
And it looks like this: 
![image](https://user-images.githubusercontent.com/47619514/79479497-764d9880-802a-11ea-9620-846469fc1c12.png)

**Comment by philsinatra** [comment]
I'd recommend keeping your customizations in place. I haven't had anyone else report this issue and I can reproduce it on my end. If I get another report of this background not showing I'll revisit this issue.
